### ISSUE TITLE
Parsing of some expressions is very slow.

### ISSUE THREAD

**Issue by kirkdsayre** [elision/elision#171]
In particular parsing a string like "enable(DEFAULT)" or "disable(DEFAULT)" takes much longer than desired. In Hyperion, rulesets are being enabled and disabled during H-chart execution by parsing strings like the given strings. According to JProfiler, almost 100% of the time spent running the H-chart algorithm is spent in Elision parsing the ruleset enable/disable strings.

**Comment by sprowell** [comment]
I don't check in enough.  Yes... this can be closed.  Closing.
